# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hello(object):
    def setupUi(self, Hello):
        Hello.setObjectName("Hello")
        Hello.resize(572, 363)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Hello.sizePolicy().hasHeightForWidth())
        Hello.setSizePolicy(sizePolicy)
        Hello.setMouseTracking(False)
        self.gridLayout = QtWidgets.QGridLayout(Hello)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Hello)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 40, 151, 216))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton_action = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_action.sizePolicy().hasHeightForWidth())
        self.pushButton_action.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_action.setFont(font)
        self.pushButton_action.setObjectName("pushButton_action")
        self.verticalLayout.addWidget(self.pushButton_action)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.pushButton_close = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout.addWidget(self.pushButton_close)
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.label_machine_sirius = QtWidgets.QLabel(self.tab2)
        self.label_machine_sirius.setGeometry(QtCore.QRect(20, 0, 521, 321))
        self.label_machine_sirius.setText("")
        self.label_machine_sirius.setPixmap(QtGui.QPixmap("sirius-maquina-layout.png"))
        self.label_machine_sirius.setScaledContents(True)
        self.label_machine_sirius.setObjectName("label_machine_sirius")
        self.status_linha_1 = QtWidgets.QLabel(self.tab2)
        self.status_linha_1.setGeometry(QtCore.QRect(110, 270, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_linha_1.setFont(font)
        self.status_linha_1.setAutoFillBackground(False)
        self.status_linha_1.setText("")
        self.status_linha_1.setPixmap(QtGui.QPixmap("led_red.png"))
        self.status_linha_1.setScaledContents(True)
        self.status_linha_1.setAlignment(QtCore.Qt.AlignCenter)
        self.status_linha_1.setObjectName("status_linha_1")
        self.label_logo_sirius = QtWidgets.QLabel(self.tab2)
        self.label_logo_sirius.setGeometry(QtCore.QRect(400, 10, 151, 91))
        self.label_logo_sirius.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_logo_sirius.setText("")
        self.label_logo_sirius.setPixmap(QtGui.QPixmap("logoSirius.png"))
        self.label_logo_sirius.setScaledContents(True)
        self.label_logo_sirius.setObjectName("label_logo_sirius")
        self.status_linha_2 = QtWidgets.QLabel(self.tab2)
        self.status_linha_2.setGeometry(QtCore.QRect(180, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_linha_2.setFont(font)
        self.status_linha_2.setAutoFillBackground(False)
        self.status_linha_2.setText("")
        self.status_linha_2.setPixmap(QtGui.QPixmap("led_red.png"))
        self.status_linha_2.setScaledContents(True)
        self.status_linha_2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_linha_2.setObjectName("status_linha_2")
        self.status_linha_3 = QtWidgets.QLabel(self.tab2)
        self.status_linha_3.setGeometry(QtCore.QRect(260, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_linha_3.setFont(font)
        self.status_linha_3.setAutoFillBackground(False)
        self.status_linha_3.setText("")
        self.status_linha_3.setPixmap(QtGui.QPixmap("led_red.png"))
        self.status_linha_3.setScaledContents(True)
        self.status_linha_3.setAlignment(QtCore.Qt.AlignCenter)
        self.status_linha_3.setObjectName("status_linha_3")
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Hello)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_clear.clicked.connect(self.lineEdit.clear)
        self.pushButton_close.clicked.connect(Hello.close)
        QtCore.QMetaObject.connectSlotsByName(Hello)

    def retranslateUi(self, Hello):
        _translate = QtCore.QCoreApplication.translate
        Hello.setWindowTitle(_translate("Hello", "Hello.ui @LNLS @GAE"))
        self.label.setText(_translate("Hello", "Nome da PV:"))
        self.label_2.setText(_translate("Hello", "Valor da PV:"))
        self.pushButton_action.setText(_translate("Hello", "Ler PV"))
        self.pushButton_clear.setText(_translate("Hello", "Clear"))
        self.pushButton_close.setText(_translate("Hello", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Hello", "PV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Hello", "Overview"))

import resources_rc
