# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarmScreen.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(613, 349)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditCount = QtWidgets.QLineEdit(Form)
        self.lineEditCount.setReadOnly(True)
        self.lineEditCount.setPlaceholderText("")
        self.lineEditCount.setClearButtonEnabled(True)
        self.lineEditCount.setObjectName("lineEditCount")
        self.verticalLayout.addWidget(self.lineEditCount)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Alarm Screen - EPS Front End"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Item"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Alarm Hour"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Alarm Text"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Alarm Class"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Alarm Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Index"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "TESTE_0"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "TESTE0"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "TESTE1"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "TESTE2"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Form", "TESTE3"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "TESTE4"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("Form", "TESTE5"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

