import sys
from epics import PV
import random
import time

pvValues = [0]*32
pv = [0]*32

#	Import EPS AI Cat Values. Generated by Excel
pv[0]=PV('IVUFE:EPS:AI_UTL-WPR-TT')
pv[1]=PV('IVUFE:EPS:AI_UTL-WRT-TT')
pv[2]=PV('IVUFE:EPS:AI_DEV-XBPM1-TT')
pv[3]=PV('IVUFE:EPS:AI_DEV-XBPM1-TT1')
pv[4]=PV('IVUFE:EPS:AI_DEV-XBPM1-TT2')
pv[5]=PV('IVUFE:EPS:AI_DEV-XBPM1-TT3')
pv[6]=PV('IVUFE:EPS:AI_DEV-XBPM1-TT4')
pv[7]=PV('IVUFE:EPS:AI_DEV-XBPM2-TT')
pv[8]=PV('IVUFE:EPS:AI_DEV-XBPM2-TT1')
pv[9]=PV('IVUFE:EPS:AI_DEV-XBPM2-TT2')
pv[10]=PV('IVUFE:EPS:AI_DEV-XBPM2-TT3')
pv[11]=PV('IVUFE:EPS:AI_DEV-XBPM2-TT4')
pv[12]=PV('IVUFE:EPS:AI_DEV-MSK-TT')
pv[13]=PV('IVUFE:EPS:AI_DEV-MSK-TT1')
pv[14]=PV('IVUFE:EPS:AI_DEV-MSK-TT2')
pv[15]=PV('IVUFE:EPS:AI_DEV-MSK-TT3')
pv[16]=PV('IVUFE:EPS:AI_DEV-MSK-TT4')
pv[17]=PV('IVUFE:EPS:AI_DEV-SLITS-TT')
pv[18]=PV('IVUFE:EPS:AI_DEV-SLITS-TT1')
pv[19]=PV('IVUFE:EPS:AI_DEV-SLITS-TT2')
pv[20]=PV('IVUFE:EPS:AI_DEV-SLITS-TT3')
pv[21]=PV('IVUFE:EPS:AI_DEV-SLITS-TT4')
pv[22]=PV('IVUFE:EPS:AI_DEV-PS-TT1')
pv[23]=PV('IVUFE:EPS:AS_UTL-CAR-PIT')
pv[24]=PV('IVUFE:EPS:AS_UTL-WPR-FIT')
pv[25]=PV('IVUFE:EPS:AS_UTL-WPR-PIT')
pv[26]=PV('IVUFE:EPS:AS_UTL-WRT-FIT')
pv[27]=PV('IVUFE:EPS:AS_UTL-WRT-PIT')
pv[28]=PV('IVUFE:EPS:AS_DEV-XBPM1-FIT')
pv[29]=PV('IVUFE:EPS:AS_DEV-XBPM2-FIT')
pv[30]=PV('IVUFE:EPS:AS_DEV-MSK-FIT')
pv[31]=PV('IVUFE:EPS:AS_DEV-SLITS-FIT')



#print (pvValues)	# Debbug

def getPvValue(pvName):
    pv = PV(pvName)
    if pv.connected:
        return pv.value
    else:
        return -1

def getRandom():
    return random.uniform(0,100)

def readAIValues():
    #	Read EPS AI Cat Values
    for i in range(32):
        pvValues[i] = pv[i].value
    return pvValues

def tamanhoArrayPVs():
    return len(readAIValues())
