from epics import PV

names = ['IVUFE:EPS:AI_UTL-WPR-TT', 'IVUFE:EPS:AI_UTL-WRT-TT', 'IVUFE:EPS:AI_DEV-XBPM1-TT', 'IVUFE:EPS:AI_DEV-XBPM1-TT1', 'IVUFE:EPS:AI_DEV-XBPM1-TT2', 'IVUFE:EPS:AI_DEV-XBPM1-TT3', 'IVUFE:EPS:AI_DEV-XBPM1-TT4', 'IVUFE:EPS:AI_DEV-XBPM2-TT', 'IVUFE:EPS:AI_DEV-XBPM2-TT1', 'IVUFE:EPS:AI_DEV-XBPM2-TT2', 'IVUFE:EPS:AI_DEV-XBPM2-TT3', 'IVUFE:EPS:AI_DEV-XBPM2-TT4', 'IVUFE:EPS:AI_DEV-MSK-TT', 'IVUFE:EPS:AI_DEV-MSK-TT1', 'IVUFE:EPS:AI_DEV-MSK-TT2', 'IVUFE:EPS:AI_DEV-MSK-TT3', 'IVUFE:EPS:AI_DEV-MSK-TT4', 'IVUFE:EPS:AI_DEV-SLITS-TT', 'IVUFE:EPS:AI_DEV-SLITS-TT1', 'IVUFE:EPS:AI_DEV-SLITS-TT2', 'IVUFE:EPS:AI_DEV-SLITS-TT3', 'IVUFE:EPS:AI_DEV-SLITS-TT4', 'IVUFE:EPS:AI_DEV-PS-TT1', 'IVUFE:EPS:AS_UTL-CAR-PIT', 'IVUFE:EPS:AS_UTL-WPR-FIT', 'IVUFE:EPS:AS_UTL-WPR-PIT', 'IVUFE:EPS:AS_UTL-WRT-FIT', 'IVUFE:EPS:AS_UTL-WRT-PIT', 'IVUFE:EPS:AS_DEV-XBPM1-FIT', 'IVUFE:EPS:AS_DEV-XBPM2-FIT', 'IVUFE:EPS:AS_DEV-MSK-FIT', 'IVUFE:EPS:AS_DEV-SLITS-FIT']

values = list()

for name in names:
    values.append(PV(name).value)

for i, value in enumerate(values):
    "setTextA" + "%d" = value % (i)
